### ISSUE TITLE
按照ReadMe步骤编译安装到Android模拟器上出错

### ISSUE THREAD

**Issue by fengguoqing** [phodal/growth#66]
使用的是Windows环境，编译安装到Android模拟器上出现以下红色报错：
Native module RNZipArchiveModule tried to override RNZipArchiveModule for module name RNZipArchive. If this was your intention, set canOverrideExistingModule=true
addNativeModule
    NativeModuleRegistryBuilder.java:122
processPackage
    NativeModuleRegistryBuilder.java:110
processPackage
    ReactInstanceManager.java:1021
createReactContext
    ReactInstanceManager.java:959
access$600
    ReactInstanceManager.java:108
doInBackground
    ReactInstanceManager.java:225
doInBackground
    ReactInstanceManager.java:203
call
    AsyncTask.java:333
run
    FutureTask.java:266
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764

请问是我的配置出错了，还是代码中存在BUG，谢谢！

**Comment by phodal** [comment]
请检查您的MainApplication.java或MainActivity.java，其中是否出现了两次 RNZipArchiveModule

**Comment by fengguoqing** [comment]
@phodal 我查找了一下，没有发现引用这个module，另外代码我还没有动过，仅仅是编译安装了一下，这块代码是编译生成的吗？

**Comment by phodal** [comment]
项目中用到了 ``react-native-zip-archive`` 应该会使用到这个模块才对。你 link 了吧？

**Comment by fengguoqing** [comment]
@phodal 对，按照指导步骤link过了，我是想参与这个项目中来，react native 新手，请多包涵

**Comment by phodal** [comment]
你再检察一下 ``MainApplication.java`` 吧？

**Comment by fengguoqing** [comment]
@phodal 谢谢，从MainApplication.java删除了重复import module之后重新编译安装，可以正常使用了
